### ISSUE TITLE
Error during startup

### ISSUE THREAD

**Issue by pimuzzo** [miurahr/docker-kandan#1]
```
kandan      | rake aborted!
kandan      | ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "users" does not exist
kandan      | LINE 5:              WHERE a.attrelid = '"users"'::regclass
kandan      |                                         ^
kandan      | :             SELECT a.attname, format_type(a.atttypid, a.atttypmod),
kandan      |                      pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
kandan      |               FROM pg_attribute a LEFT JOIN pg_attrdef d
kandan      |                 ON a.attrelid = d.adrelid AND a.attnum = d.adnum
kandan      |              WHERE a.attrelid = '"users"'::regclass
kandan      |                AND a.attnum > 0 AND NOT a.attisdropped
kandan      |              ORDER BY a.attnum
kandan      | /home/kandan/kandan/lib/tasks/kandan.rake:95:in `block (2 levels) in <top (required)>'
kandan      | Tasks: TOP => kandan:hubot_access_key
kandan      | (See full trace by running task with --trace)
kandan      | hubot key is: cat: /home/kandan/kandna/hubot-key: No such file or directory
kandan      | 2016-04-22 14:56:36,323 CRIT Supervisor running as root (no user in config file)
kandan      | 2016-04-22 14:56:36,323 WARN Included extra file "/etc/supervisor/conf.d/kandan.conf" during parsing
kandan      | 2016-04-22 14:56:36,357 INFO RPC interface 'supervisor' initialized
kandan      | 2016-04-22 14:56:36,357 CRIT Server 'unix_http_server' running without any HTTP authentication checking
kandan      | 2016-04-22 14:56:36,357 INFO supervisord started with pid 1
kandan      | 2016-04-22 14:56:37,360 INFO spawned: 'kandan' with pid 572
kandan      | 2016-04-22 14:56:38,361 INFO success: kandan entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
postgres    | ERROR:  relation "sessions" does not exist at character 315
postgres    | STATEMENT:              SELECT a.attname, format_type(a.atttypid, a.atttypmod),
postgres    |                        pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
postgres    |                 FROM pg_attribute a LEFT JOIN pg_attrdef d
postgres    |                   ON a.attrelid = d.adrelid AND a.attnum = d.adnum
postgres    |                WHERE a.attrelid = '"sessions"'::regclass
postgres    |                  AND a.attnum > 0 AND NOT a.attisdropped
postgres    |                ORDER BY a.attnum
postgres    |   
postgres    | ERROR:  relation "sessions" does not exist at character 315
postgres    | STATEMENT:              SELECT a.attname, format_type(a.atttypid, a.atttypmod),
postgres    |                        pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
postgres    |                 FROM pg_attribute a LEFT JOIN pg_attrdef d
postgres    |                   ON a.attrelid = d.adrelid AND a.attnum = d.adnum
postgres    |                WHERE a.attrelid = '"sessions"'::regclass
postgres    |                  AND a.attnum > 0 AND NOT a.attisdropped
postgres    |                ORDER BY a.attnum
```

**Comment by miurahr** [comment]
At least, here is a typo to be fixed.

```
hubot key is: cat: /home/kandan/kandna/hubot-key: No such file or directory
```

`kandna` shoudl be `kandan`

I do not know  why database accesses become error in first impression.

**Comment by miurahr** [comment]
Do you configure PostgreSQL server in your environment and configure properly?
Please check again your docker-compose.yml that is configure to point your PostgreSQL server or configure to use docker image version of PostgreSQL server?

**Comment by pimuzzo** [comment]
I'm using this docker compose file:

```
version: '2'
services:
  postgres:
    container_name: postgres
    environment:
      POSTGRES_USER: kandan
      POSTGRES_DB: kandan_production
      POSTGRES_PASSWORD: hogefuga
    image: postgres
  kandan:
    restart: always
    container_name: kandan
    image: miurahr/kandan
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: kandan_production
      DB_USER: kandan
      DB_PASS: hogefuga
    ports:
    - 3000:3000
```

and I launch it with: `docker-compose -f kandan.yml up --force-recreate`
